# Generated by Django 6.1 on 2026-08-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('info', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('photo_url', models.URLField()),
                ('lyric', models.JSONField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='songs.artist')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['id'],
            },
        ),
    ]
