# Generated by Django 6.1 on 2026-08-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=100),
        ),
    ]
